services:

  api_service:
    environment:
      - ENV=local
    container_name: app_poetry
    image: image_poetry
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:8000/ || exit 1"
        ]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
